apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  startegy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql 
      volumeMounts:
        - name: mysql-presistent-storage
          mountPath: /var/lib/mysql
        - name: usermanagement-dbcreation-script
          mountPath: /docker-entrypoint-initdb.d
      volumes: 
        - name: mysql-presistent-storage
          PersistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: usermanagement-dbcreation-script
          ConfigMap:
            name: usermanagement-dbcreation-script
