apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: gke-storage-class
provisioner: pd.csi.storage.gke.io
volumeBinding: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-balanced
  