apiVersion: v1 
kind: Service
metadata:
  name: user-mgmt-webapp-svc
  labels:
    app: user-mgmt-webapp
spec:
  type: LoadBalancer
  selector:
    app: user-mgmt-webapp
  ports:
    - port: 80
      targetPort: 8080 
