apiVersion: v1 
kind: Service
metadata:
  name: myapp1-nodeport-service
spec:  
  type: NodePort 
  selector:
    app: myapp
  ports: 
    - name: http
      port: 80 #service Port
      targetPort: 80 #container Port
      nodePort: 30080 #nodeport